79 implement ezy app user added event
youngmonkeys/ezyfox-server pull request #85
Opened 2022-03-14 15:43 UTC by changxdevelop

### What is the purpose of this pull request?

### When do you want to merge?

2022-04-12 16:42 UTC, tvd12 requested changes
@changxdevelop PLTAL

2022-04-12 16:42 UTC, tvd12 commented on ezyfox-server-core/src/main/java/com/tvd12/ezyfoxserver/constant/EzyEventType.java
> +    APP_USER_ADDED(37);
nên là `USER_ACCESSED_APP(28)` em ạ

2022-04-12 16:42 UTC, tvd12 commented on ezyfox-server-core/src/main/java/com/tvd12/ezyfoxserver/event/EzyAppUserAddedEvent.java
> +public interface EzyAppUserAddedEvent extends EzyUserEvent {
nên là `EzyUserAccessedAppEvent`

2022-04-12 16:42 UTC, tvd12 commented on ezyfox-server-core/src/main/java/com/tvd12/ezyfoxserver/event/EzySimpleAppUserAddedEvent.java
> +public class EzySimpleAppUserAddedEvent
nên là `EzySimpleUserAccessedAppEvent`

2022-04-12 16:42 UTC, tvd12 commented on ezyfox-server-core/src/main/java/com/tvd12/ezyfoxserver/controller/EzyAccessAppController.java
> +	protected EzyAppUserAddedEvent newAppUserAddedEvent(EzyUser user) { return new EzySimpleAppUserAddedEvent(user); }
nên là `newAccessedAppEvent`

2022-04-14 15:33 UTC, changxdevelop commented
em đã fix hết các lỗi này

2022-04-14 15:33 UTC, closed without merging